version: '3.8'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin     # Default MinIO root user
      MINIO_ROOT_PASSWORD: minioadmin  # Default MinIO root password
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
